[engine]
binary_path = "engine/stockfish"
database_path = "file:lichess.sqlite"  # sebenarnya URI

[engine.config]
EvalFile = "engine/nn-1c0000000000.nnue"
MultiPV = 1
Threads = 4
Hash = 2048

[importer]
cpu_count = 4
batch_size = 1000
dump_path = "dump"

[play_web.flask]
debug = true
port = 9900

[play_cli]
book_move = 2

[play_cli.user]
multipv = 2
analysis_depth.min = 24
analysis_depth.max = 50

[play_cli.engine]
multipv = 3
analysis_depth.min = 10
analysis_depth.max = 20
score_cutoff = 100       # cp
